Traceback (most recent call last):
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\seanc\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\nbclient\client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#find average of all stored results
avg_vary_feat = pd.DataFrame(columns=['mean', 'std', 'time'])
for i in range(1, 67):
    i = str(i)
    s = pd.Series(vary_feat.T[i].mean(axis=1), name=i, index=['mean','std', 'time'])
    avg_vary_feat = avg_vary_feat.append(s)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_17456/325629898.py[0m in [0;36m<module>[1;34m[0m
[0;32m      3[0m [1;32mfor[0m [0mi[0m [1;32min[0m [0mrange[0m[1;33m([0m[1;36m1[0m[1;33m,[0m [1;36m67[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m     [0mi[0m [1;33m=[0m [0mstr[0m[1;33m([0m[0mi[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 5[1;33m     [0ms[0m [1;33m=[0m [0mpd[0m[1;33m.[0m[0mSeries[0m[1;33m([0m[0mvary_feat[0m[1;33m.[0m[0mT[0m[1;33m[[0m[0mi[0m[1;33m][0m[1;33m.[0m[0mmean[0m[1;33m([0m[0maxis[0m[1;33m=[0m[1;36m1[0m[1;33m)[0m[1;33m,[0m [0mname[0m[1;33m=[0m[0mi[0m[1;33m,[0m [0mindex[0m[1;33m=[0m[1;33m[[0m[1;34m'mean'[0m[1;33m,[0m[1;34m'std'[0m[1;33m,[0m [1;34m'time'[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      6[0m     [0mavg_vary_feat[0m [1;33m=[0m [0mavg_vary_feat[0m[1;33m.[0m[0mappend[0m[1;33m([0m[0ms[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Roaming\Python\Python38\site-packages\pandas\core\generic.py[0m in [0;36mstat_func[1;34m(self, axis, skipna, level, numeric_only, **kwargs)[0m
[0;32m  11212[0m         [1;32mif[0m [0mlevel[0m [1;32mis[0m [1;32mnot[0m [1;32mNone[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m  11213[0m             [1;32mreturn[0m [0mself[0m[1;33m.[0m[0m_agg_by_level[0m[1;33m([0m[0mname[0m[1;33m,[0m [0maxis[0m[1;33m=[0m[0maxis[0m[1;33m,[0m [0mlevel[0m[1;33m=[0m[0mlevel[0m[1;33m,[0m [0mskipna[0m[1;33m=[0m[0mskipna[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m> 11214[1;33m         return self._reduce(
[0m[0;32m  11215[0m             [0mf[0m[1;33m,[0m [0mname[0m[1;33m,[0m [0maxis[0m[1;33m=[0m[0maxis[0m[1;33m,[0m [0mskipna[0m[1;33m=[0m[0mskipna[0m[1;33m,[0m [0mnumeric_only[0m[1;33m=[0m[0mnumeric_only[0m[1;33m[0m[1;33m[0m[0m
[0;32m  11216[0m         )

[1;32m~\AppData\Roaming\Python\Python38\site-packages\pandas\core\series.py[0m in [0;36m_reduce[1;34m(self, op, name, axis, skipna, numeric_only, filter_type, **kwds)[0m
[0;32m   3867[0m [1;33m[0m[0m
[0;32m   3868[0m         [1;32mif[0m [0maxis[0m [1;32mis[0m [1;32mnot[0m [1;32mNone[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 3869[1;33m             [0mself[0m[1;33m.[0m[0m_get_axis_number[0m[1;33m([0m[0maxis[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   3870[0m [1;33m[0m[0m
[0;32m   3871[0m         [1;32mif[0m [0misinstance[0m[1;33m([0m[0mdelegate[0m[1;33m,[0m [0mCategorical[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Roaming\Python\Python38\site-packages\pandas\core\generic.py[0m in [0;36m_get_axis_number[1;34m(cls, axis)[0m
[0;32m    405[0m             [1;32mexcept[0m [0mKeyError[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    406[0m                 [1;32mpass[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 407[1;33m         [1;32mraise[0m [0mValueError[0m[1;33m([0m[1;34mf"No axis named {axis} for object type {cls}"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    408[0m [1;33m[0m[0m
[0;32m    409[0m     [1;33m@[0m[0mclassmethod[0m[1;33m[0m[1;33m[0m[0m

[1;31mValueError[0m: No axis named 1 for object type <class 'pandas.core.series.Series'>
ValueError: No axis named 1 for object type <class 'pandas.core.series.Series'>

